name: covid-sa-savegraph

on:
  schedule:
    - cron: '30 8-10 * * 5' # runs from 6pm to 8pm ADL time on Friday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Execute script
        run: python covid-sa.py
          
      - name: Commit if changed
        uses: stefanzweifel/git-auto-commit-action@v4
        