name: covid-sa-savegraph

on:
  schedule:
    - cron: '30 */2 * * *' # runs on 30 min offset for SA every 2 hours

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Load cached $HOME/.local
        uses: actions/cache@v2.1.6
        with:
          path: ~/.local
          key: dotlocal-${{ runner.os }}-${{ hashFiles('.github/workflows/covid-sa-savegraph.yml') }}
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute script
        run: python covid-sa.py
          
      - name: commit if changed
        uses: stefanzweifel/git-auto-commit-action@v4
        